name: Schedule Discussion Post Action
description:
  This action will create a discussion post in a repository at a scheduled time.
author: Ben Balter
runs:
  using: node20
  main: dist/index.js
inputs:
  repo_token:
    description: The default GitHub Actions token
    required: false
    default: ${{ github.token }}
  discussion_token:
    description: A PAT with `discussion:write` scope for the target repository
    required: true
